# -*- coding: utf-8 -*-
"""Python_Class_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V1xVFt3-WVzqBL_hPNKFrXT5k7YVfURX
"""

# Part 01: basics Python
# Variables
name = " Salek Data Lab"
year = 2026
pi = 3.1416
is_ready = True
print( name)
print(year)

# Data Types
print(type(name)) # str: string
print(type(year)) #  Int :Integer
print(type(pi)) # Decimal : Float

# List: always in third bracket
scores = [ 100,50,200,150]
print("Scores:",scores)
print("Average:", sum(scores)/len(scores)) # length:len

# Dictionary : Always in 2nd bracket
student = {
    "name" : "Salek",
    "age" : 24,
    "department" : "Statistics",
    "Score" : 100
}
print("Student:", student)

# Tuple(Parenthesis)
coordinates = (20.5, 50.5)
print("Coordinates:",coordinates )

# Set : Uniques values
unique_scores = set(scores)
print("Unique scores:",unique_scores)

#  Condition + Loop
for score in scores:
  if score >= 80:
    grade = "A"
  elif score >= 70:
    grade = "B"
  else:
    grade = "c"
  print(score, grade)

# Function
def calculate_bmi(weight,height):
  return weight/(height**2)
  bmi = calculate_bmi(72,1.65)
  print("BMI:",round(bmi,2))

# Part 02: Basics of NUMPY
import numpy as np # import + numpy+ as+ short name
x = np.array([1,2,3,4,5])
print("Array:", x)
print("Mean:\n",np.mean(x))
print("Median:\n", np.median(x))
print("Standard Deviation:\n",np.std(x, ddof =1))
print("Squares:", x**2)

# How to create a matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n",matrix) # \n:used when next part shift to the below

# Random data
np.random.seed(42)
random_data =np.random.normal(
    loc=100,
    scale = 15,
    size = 1000
)

print("First 10 values:")
print(random_data[:10])

# Histogram
import matplotlib.pyplot as plt # used for drawing figure(seaborn:sns)
plt.figure(figsize=(8,5))
plt.hist(random_data,bins = 30, edgecolor ="black")
plt.title("Normal Random Sample")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

# Pandas
import pandas as pd
rng = np.random.default_rng(42)
n = 500 # observations
# Create Sample Dataset
df = pd.DataFrame({
    "id": np.arange(1,n+1),
    "age": rng.integers(18,80,n),
    "gender": rng.choice (
        ["Female", "Male","female","male"],
        n
    ),
    "bmi" :rng.normal(25,4,n),
    "smoker": rng.choice(
        ["Yes","No", None],
        n,
        p = [0.20, 0.75, 0.05]
    ),
    "outcome": rng.binomial(1,0.25,n)
})

# Explore data
print(df.head())
print("\nShape:", df.shape)
print(df.dtypes)
print("\nSummary:")
print(df.describe())

# Add missing BMI Values
missing_rows = rng.choice(
    df.index,
    25,
    replace = False
)
df.loc[missing_rows,"bmi"] = np.nan

# Add duplicate rows
df= pd.concat(
    [df, df.iloc[:5]],
   ignore_index=True
)
print("\nAfter adding duplicates:", df.shape)